paysys/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.contrib import admin
from userrating.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^userrating/', include('userrating.urls', namespace="userrating")),
    url('^login/', auth_views.login, {'template_name': 'userrating/login.html'},
            name="login"),
    url('^logout/', auth_views.logout, {'next_page': '/login/'}, name="login"),

    url(r'^admin/', include(admin.site.urls)),
]

urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sales/$', views.sales_list, name='sales'),
    url(r'^purchases/$', views.purchases_list, name='purchases'),
    url(r'^purchases/(?P<pk>[0-9]+)/$', views.purchase_detail, name='purchase_detail'),
    url(r'^purchases/(?P<pk>[0-9]+)/edit/$', views.purchase_review_edit, name='purchase_review_edit'),
    url(r'^sales/(?P<pk>[0-9]+)/$', views.sale_detail, name='sale_detail'),
    url(r'^sales/(?P<pk>[0-9]+)/edit/$', views.sale_review_edit, name='sale_review_edit'),
   
]

userrating/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sales/$', views.sales_list, name='sales'),
    url(r'^purchases/$', views.purchases_list, name='purchases'),
    url(r'^purchases/(?P<pk>[0-9]+)/$', views.purchase_detail, name='purchase_detail'),
    url(r'^sales/(?P<pk>[0-9]+)/$', views.sale_detail, name='sale_detail'),
   
]

userrating/views.py
import urllib.request
import urllib.parse
import urllib.error
from datetime import datetime, timedelta
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages
from django.conf import settings
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect
from django.utils import timezone

from .models import *
from .forms import UserReviewForm


@login_required
def index(request):
    return render(request, 'userrating/index.html')


@login_required
def sales_list(request):
    sales = ItemSale.objects.filter(seller=request.user)
    return render(request, 'userrating/sales.html', {'sales': sales})


@login_required
def purchases_list(request):
    purchases = ItemSale.objects.filter(buyer=request.user)
    return render(request, 'userrating/purchases.html',
                    {'purchases': purchases})

@login_required
def purchase_detail(request, pk):
	purchase = ItemSale.objects.get(pk=pk)
	
	if request.method == 'POST':
		form = UserReviewForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('userrating:purchase_detail', args=[purchase.pk]))
		if edit_form.is_valid():
			edit_form.save()
			return HttpResponseRedirect(reverse('userrating:purchase_detail', args=[purchase.pk]))	
	else:
		data = {'itemsale': purchase , 'user': purchase.buyer}
		form = UserReviewForm(initial=data)

	try:
		review = UserReview.objects.get(itemsale=purchase)
	except:
		review = None

	edit_form = UserReviewForm(instance=review)

	deadline =  purchase.created + timedelta(days=31)
	
	if deadline >= timezone.now():
		show = True
	else:
		show = False	

	return render(request, 'userrating/purchase_detail.html', {'purchase': purchase, 'form': form, 'show': show, 'review': review, 'edit_form': edit_form})


@login_required
def sale_detail(request, pk):
	sale = ItemSale.objects.get(pk=pk)
	start_date = sale.created
	deadline =  start_date + timedelta(days=31)
	
	try:
		review = UserReview.objects.get(itemsale=sale)
	except:
		review = None

	edit_form = UserReviewForm(instance=review)
	
	if deadline >= start_date:
		show = True
	else:
		show = False	

	if request.method == 'POST':
		form = UserReviewForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('userrating:sale_detail', args=[sale.pk]))
		if edit_form.is_valid():
			edit_form.save()
			return HttpResponseRedirect(reverse('userrating:sale_detail', args=[sale.pk]))
				
	else:
		data = {'itemsale': sale , 'user': sale.seller}
		form = UserReviewForm(initial=data)

	return render(request, 'userrating/sale_detail.html', {'sale': sale, 'form': form, 'show': show, 'review': review, 'edit_form': edit_form})	



templates/userrating/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Payment Processing System - Paynow Integration">
    <meta name="author" content="charlek" >


    <title>{% block title %}{% endblock %} - Payment Dashboard - Paynow Integration</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'userrating/css/bootstrap.min.css' %}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'userrating/css/dashboard.css' %}" />
    <script src="{% static 'userrating/js/jquery.min.js' %}"></script>
    <script type="text/javascript">
    jQuery('#edit_form').hide();
    </script>
    <script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#hideshow').on('click', function(event) {        
             jQuery('#edit_form').toggle('show');
        });
    });
    </script>

</head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">User Rating</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
           <li><a href="{ url 'paynow:my_profile' %}">{{ user.username }} ({{ user.email }})</a></li>
           <li><a href="/logout/">Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <p>
          <ul class="nav nav-sidebar">
            <li class="active"><a href="{% url 'userrating:index' %}">User Ratings Home<span class="sr-only">(current)</span></a></li>
           <li><a href="{% url 'userrating:sales' %}">Sales</a></li>
            <li><a href="{% url 'userrating:purchases' %}">Purchases</a></li>
          </ul>
          </p>
          {% block cashier_side_menu %}{% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
         <!-- <h1 class="page-header">Dashboard</h1>
          <h2 class="sub-header">Section title</h2> -->

          {% if messages %}
          <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-danger">
                <ul class="messages">
    		{% for message in messages %}
    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    		{% endfor %}
                </ul>
            </div>
        </div>
        </div>
	{% endif %}
          {% block content %}{% endblock %}

        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'userrating/js/jquery.min.js' %}"></script>
    <script src="{% static 'userrating/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/userrating/index.html
{% extends "userrating/base.html" %}

{% block title %}User Sales{% endblock %}

{% block content %}
 Start of system
{% endblock %}

templates/userrating/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="charlek" >
    <link rel="icon" href="../../favicon.ico">

    <title>Login - UserRating System</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'userrating/css/bootstrap.min.css' %}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'userrating/css/signin.css' %}" />


  </head>

  <body>

    <div class="container">
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
	<p>Your username and password didn't match. Please try again.</p>
	</div>
{% endif %}
        <h1 class="page-header">User Rating</h1>
	<p>
	

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
	</p>
    </div> <!-- /container -->
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'userrating/js/jquery.min.js' %}"></script>
    <script src="{% static 'userrating/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/userrating/purchase_detail.html
{% extends "userrating/base.html" %}

{% block title %}{{ purchase.title }}{% endblock %}

{% block content %}
<div class="container">
	<h1>{{ purchase.title }}</h1>
	<p>SELLER: {{purchase.seller}}</p>
	<p>DATE: {{purchase.created}}</p>


{% if not review and show %}
	<input type='button' id='hideshow' value='Add Rating' class="btn btn-info">
	<div id="edit_form">	
		<div class="reviewform">
			<form action="." method="post">
				{% csrf_token %}
			    {{ form.as_p }}
			    <button class="btn btn-info" type="submit">Submit Review</button>
			</form> 
		</div>
	</div>	
{% elif review and show %}
	<p>Rating: {{ review.rating }} stars</p>
	<a class="btn btn-info" href="{% url 'userrating:purchase_review_edit' pk=purchase.pk %}">Edit Rating</a>	 	   
{% endif %}
	</div>	
{% endblock %}

templates/userrating/purchase_review_edit.html
{% extends "userrating/base.html" %}

{% block title %}{{ purchase.title }}{% endblock %}

{% block content %}
<h1>Edit Review</h1>

<div class="reviewform">
	<form action="." method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-info" type="submit">Save</button>
	</form>
</div>

{% endblock %}	

templates/userrating/purchases.html
{% extends "userrating/base.html" %}

{% block title %}User Purchases{% endblock %}

{% block content %}
<h1> My Purchases</h1>
<ul>
{% for purchase in purchases %}
<li><a href="{% url 'userrating:purchase_detail' pk=purchase.pk%}">{{ purchase.title }}</a></li>

{% endfor %}
</ul>
{% endblock %}

templates/userrating/review.html
{% extends "userrating/base.html" %}

{% block title %} User Purchases {% endblock %}

{% block content %}

<div class="container">
	<div class="reviewform">	
		<form role="form" method="post">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <button type="submit" class="btn btn-info">Save</button>
		</form>
	</div>
</div>    

{% endblock %}

templates/userrating/sale_detail.html
{% extends "userrating/base.html" %}

{% block title %}{{ purchase.title }}{% endblock %}

{% block content %}
<div class="container">
	<h1>{{ sale.title }}</h1>
	<p>BUYER: {{sale.buyer}}</p>
	<p>DATE: {{sale.created}}</p>

{% if not review and show %}
	<input type='button' id='hideshow' value='Add Rating' class="btn btn-info">
	<div id="edit_form">	
		<div class="reviewform">
			<form action="." method="post">
				{% csrf_token %}
			    {{ form.as_p }}
			    <button class="btn btn-info" type="submit">Submit Review</button>
			</form> 
		</div>
	</div>	
{% elif review and show %}
	<p>Rating: {{ review.rating }} stars</p>
	<a class="btn btn-info" href="{% url 'userrating:sale_review_edit' pk=sale.pk %}">Edit Rating</a>	 	   
{% endif %}

</div>	
{% endblock %}

templates/userrating/sale_review_edit.html
{% extends "userrating/base.html" %}

{% block title %}{{ sale.title }}{% endblock %}

{% block content %}
<h1>Edit Review</h1>

<div class="reviewform">
	<form action="." method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-info" type="submit">Save</button>
	</form>
</div>

{% endblock %}	

templates/userrating/sales.html
{% extends "userrating/base.html" %}

{% block title %}User Sales{% endblock %}

{% block content %}
<h1> My Sales</h1>

<ul>
{% for sale in sales %}
<li><a href="{% url 'userrating:sale_detail' pk=sale.pk%}">{{ sale.title }}</a></li>

{% endfor %}
</ul>
{% endblock %}